on: 
  workflow_call:
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:            
    - uses: graalvm/setup-graalvm@b11d36630f94ed5864e0a680a979b5afde449e9d
      with:
        version: 'latest'
        java-version: '17'
        set-java-home: 'true'
        cache: maven
        github-token: ${{ secrets.GITHUB_TOKEN }}
  
