on: 
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      module:
        required: true
        type: string
      modulePath:
        required: true
        type: string
        
jobs:
  buildpacks:
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps: 
    - run: |
        echo "path=$(pwd)" >> $GITHUB_ENV
        echo "home=$HOME" >> $GITHUB_ENV
        
#     - name: Download .m2
#       uses: actions/download-artifact@v3.0.1
#       with:
#         name:  m2
#         path: ${{ env.home }}/.m2/repository/com/elpsykongroo
        
    - uses: actions/download-artifact@v3.0.1
      with:
        name:  package
        
    - uses: actions/cache@v3.2.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/ ${{ inputs.modulePath }}pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven- 
        
    - uses: ScribeMD/docker-cache@0.2.7
      with:
        key: docker-${{ runner.os }}-${{ github.workflow_ref }}
         
    - uses: labman4/buildpacks-action@master
      with:
        image:  ${{ inputs.module }}
        tag: native
        path: '${{ env.path }}/${{ inputs.modulePath }}/'
        builder: 'paketobuildpacks/builder:0.1.303-tiny'
        env: 'BP_JVM_VERSION=17.0.5 JAVA_TOOL_OPTIONS=-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/ BP_NATIVE_IMAGE=true'
        map_env: 'BP_MAVEN_BUILD_ARGUMENTS="-Dmaven.test.skip=true --no-transfer-progress package "'
        volume: ${{ env.home }}
              
    - name: Push To hub
      uses: redhat-actions/push-to-registry@v2.7
      with:
        image: ${{ inputs.module }}
        registry: docker.io/labman4
        tags: "native"
        username:  ${{ secrets.REGISTRY_NAME }}
        password:  ${{ secrets.REGISTRY_PASS }}  
      
    - name: Push To quay
      uses: redhat-actions/push-to-registry@v2.7
      with:
        image: ${{ inputs.module }}
        registry: quay.io/elpsykongroo
        tags: "native"
        username:  ${{ secrets.QUAY_REGISTRY_NAME }}
        password:  ${{ secrets.QUAY_REGISTRY_PASS }}
        
    - name: Push To harbor
      uses: redhat-actions/push-to-registry@v2.7
      with:
        image: ${{ inputs.module }}
        registry: registry.elpsykongroo.com/library
        tags: "native"
        username:  ${{ secrets.REGISTRY_PRIVATE_NAME }}
        password:  ${{ secrets.REGISTRY_PRIVATE_PASS }}
      continue-on-error: true 

