on: 
  workflow_call:
    secrets: 
      REGISTRY_NAME:
        required: true
      REGISTRY_PASS:
        required: true    
jobs:
  pre:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
            
      - name: Set up Graalvm
        uses: graalvm/setup-graalvm@d01f5f519f35cf82b318133761fd8b674632a8fe
        with:
          version: 'latest'
          java-version: '17'
          set-java-home: 'true'
          cache: maven
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
       
      - name: Cache local Maven repository
        uses: actions/cache@v3.2.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-        
        
      - name: pwd
        run: |
          echo "path=$(pwd)" >> $GITHUB_ENV
          
      - name: package client
        run: | 
          mvn package -DskipTests
        
      - name: package
        run: |
          mvn -P native package -DskipTests -f  ${{ env.path }}/gateway/pom.xml 
          
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
      
      - name: Build image
  #       uses: mamezou-tech/buildpacks-action@master
        uses: labman4/buildpacks-action@0.27.0
        with:
          image: 'gateway'
          tag: pre
#           path: '${{ env.path }}/gateway/'
          builder: 'paketobuildpacks/builder:0.1.303-tiny'
          env: 'BP_JVM_VERSION=17.0.5 JAVA_TOOL_OPTIONS=-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/ BP_NATIVE_IMAGE=true BP_MAVEN_POM_FILE=gateway/pom.xml'
          map_env: 'BP_MAVEN_BUILD_ARGUMENTS="-Dmaven.test.skip=true --no-transfer-progress package -f  gateway/pom.xml"'
              
      - name: Push To Registry
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: gateway
          registry: docker.io/labman4
          tags: "pre"
          username:  ${{ secrets.REGISTRY_NAME }}
          password:  ${{ secrets.REGISTRY_PASS }}
