on: 
  workflow_call:
    secrets: 
      REGISTRY_NAME:
        required: true
      REGISTRY_PASS:
        required: true    
  
jobs:
  buildpacks:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: ubuntu-latest
    steps: 
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name:  ${{ env.name }}-package
        
    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@0.2.7
      with:
        key: docker-${{ runner.os }}-{hash}

    - run: |
        echo "path=$(pwd)" >> $GITHUB_ENV
        echo "home=$HOME" >> $GITHUB_ENV
   
    - run: |
      
    - name: Build image
      uses: labman4/buildpacks-action@master
      with:
        image: 'gateway'
        tag: native
        path: '${{ env.path }}/gateway/'
        builder: 'paketobuildpacks/builder:0.1.303-tiny'
        env: 'BP_JVM_VERSION=17.0.5 JAVA_TOOL_OPTIONS=-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/ BP_NATIVE_IMAGE=true'
        map_env: 'BP_MAVEN_BUILD_ARGUMENTS="-Dmaven.test.skip=true --no-transfer-progress package "'
        volume: ${{ env.path }}
      
    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.7
      with:
        image: gateway
        registry: docker.io/labman4
        tags: "native"
        username:  ${{ secrets.REGISTRY_NAME }}
        password:  ${{ secrets.REGISTRY_PASS }}

