on: 
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build image
      uses: mamezou-tech/buildpacks-action@master
      with:
        image: 'registry.elpsykongroo.com/library/demo'
#         path: 'samples/apps/java-maven/'
        builder: 'paketobuildpacks/builder:0.1.303-tiny'
        env: 'BP_JVM_VERSION=17.0.5'
