name: build online
on: 
  workflow_call:
  
jobs:
   build-online:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: [ubuntu-latest]
    steps: 
      - name: Checkout Code
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
            
      - name: Set up Graalvm
        uses: graalvm/setup-graalvm@d01f5f519f35cf82b318133761fd8b674632a8fe
        with:
          version: 'latest'
          java-version: '17'
          set-java-home: 'true'
          cache: maven
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'
       
      - name: Cache local Maven repository
        uses: actions/cache@v3.2.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 
            
      - name: Build native image
        run: |
          mvn -Pnative,nativeTest package -DskipTests
