on: 
  workflow_call:
    inputs:
      module:
        required: true
        type: string
      moduleName:
        required: false
        type: string
        
jobs:
  pre:
    environment: native-image
    runs-on: [ubuntu-latest]
    continue-on-error: true 
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
            
      - uses: ScribeMD/docker-cache@0.2.7
        with:
          key: docker-${{ runner.os }}-${{ github.workflow_ref }}
          
      - uses: graalvm/setup-graalvm@d01f5f519f35cf82b318133761fd8b674632a8fe
        with:
          version: 'latest'
          java-version: '17'
          set-java-home: 'true'
          cache: maven
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
       
      - uses: actions/cache@v3.2.2
        with:
          path: ~/.m2/repository
          key:  ${{ runner.os }}-maven-${{ hashFiles('${{ inputs.module }}/${{ inputs.moduleName }}/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('${{ inputs.module }}/${{ inputs.moduleName }}/pom.xml') }}
 
      - run: |
          echo "home=$HOME" >> $GITHUB_ENV
          echo "path=$(pwd)" >> $GITHUB_ENV
          
      - run: | 
          mvn package install -DskipTests
        
      - run: |
          mvn -P native package -DskipTests -f  ${{ env.path }}/${{ inputs.module }}/${{ inputs.moduleName }}pom.xml 
      
      - name: Build image
        uses: labman4/buildpacks-action@master
        with:
          image: ${{ inputs.module }}
          tag: pre
          path: '${{ env.path }}/${{ inputs.module }}/${{ inputs.moduleName }}'
          builder: 'paketobuildpacks/builder:0.1.303-tiny'
          env: 'BP_JVM_VERSION=17.0.5 JAVA_TOOL_OPTIONS=-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/ BP_NATIVE_IMAGE=true '
          map_env: 'BP_MAVEN_BUILD_ARGUMENTS="-Dmaven.test.skip=true --no-transfer-progress package "'
          volume: ${{ env.home }}
              
      - name: Push To hub
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ inputs.module }}
          registry: docker.io/labman4
          tags: "pre"
          username:  ${{ secrets.REGISTRY_NAME }}
          password:  ${{ secrets.REGISTRY_PASS }}  

      - name: Push To quay
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ inputs.module }}
          registry: quay.io/elpsykongroo
          tags: "pre"
          username:  ${{ secrets.QUAY_REGISTRY_NAME }}
          password:  ${{ secrets.QUAY_REGISTRY_PASS }}

      - name: Push To harbor
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ inputs.module }}
          registry: registry.elpsykongroo.com/library
          tags: "pre"
          username:  ${{ secrets.REGISTRY_PRIVATE_NAME }}
          password:  ${{ secrets.REGISTRY_PRIVATE_PASS }}
     
  
