on: 
  workflow_call:
  
jobs:
  buildpacks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
#     - name: init env
#       run: |
#          touch  env
#          echo -e ' BP_NATIVE_IMAGE=true BP_NATIVE_IMAGE_BUILD_ARGUMENTS=--initialize-at-build-time=ch.qos.logback.classic.Logger \c' |cat >> env
#          echo -e ' BP_MAVEN_BUILD_ARGUMENTS=-Pnative nativeTest package -DskipTests -P prod BP_JVM_VERSION=17.0.5 \c' |cat >> env
#          cat env
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name:  ${{ env.name }}-build
        
    - name: Build image
      uses: labman4/buildpacks-action@0.27.0
      with:
        image: 'registry.elpsykongroo.com/library/demo'
#         path: 'samples/apps/java-maven/'
        builder: 'paketobuildpacks/builder:0.1.303-tiny'
        env: 'BP_JVM_VERSION=17.0.5 JAVA_TOOL_OPTIONS=-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/ BP_NATIVE_IMAGE=true BP_NATIVE_IMAGE_BUILD_ARGUMENTS=--initialize-at-build-time=ch.qos.logback.classic.Logger'
        map_env: 'BP_MAVEN_BUILD_ARGUMENTS=package -Pnative,nativeTest -DskipTests'
        
    - name: Show build command
      run: echo ${{ steps.build.outputs.command }}
 
