name: Native builder
on: 
  workflow_call:
  
jobs:
  build:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: [ubuntu-latest]
    steps: 
      - name: Download report artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name:  ${{ env.name }}-build
      
      - name: Build native image
        run: |
          mvn -Pnative,nativeTest package -DskipTests  -P prod
