 name: Codecy coverage reporter
 on:
   workflow_call:
     inputs:
       config-path:
         required: true
         type: string
     secrets:
       envPAT:
         required: true

 jobs:
   codacy_coverage:
     runs-on: ubuntu-latest
     steps:
     - uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
