
name: host deploy 
on: 
  workflow_call:
    inputs:
      module:
        required: true
        type: string
jobs:
  deploy:
    runs-on: [self-hosted]
    continue-on-error: true 
    steps:
      - if: ${{ github.ref_name == 'main' }}
        run: |
          helm uninstall -n demo ${{ inputs.module }}
        continue-on-error: false 
       
      - if: ${{ github.ref_name == 'develop' }}
        run: |
          helm uninstall -n native ${{ inputs.module }}
        continue-on-error: false 

      - if: ${{ github.ref_name == 'main' }}
        run: |
          helm install -n demo ${{ inputs.module }} ~/code/helm/charts/demo/${{ inputs.module }}
        continue-on-error: true 
        
      - if: ${{ github.ref_name == 'develop'}}
        run: |
          helm install -n native ${{ inputs.module }} ~/code/helm/charts/demo/${{ inputs.module }} -f ~/code/helm/charts/demo/${{ inputs.module }}/values-pre.yaml
        continue-on-error: true 
