on: 
  workflow_call:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v3.5.3
    
    - uses: graalvm/setup-graalvm@b11d36630f94ed5864e0a680a979b5afde449e9d
      with:
        version: 'latest'
        java-version: '17'
        set-java-home: 'true'
        cache: maven
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: maven-repo
        path: ~/.m2/repository
