name: host deploy 
on: 
  workflow_call:
    inputs:
      module:
        required: true
        type: string
      env:
        required: false
        type: string
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: depoly with helm
        run: |
          helm upgrade -n demo ${{ inputs.module }}${{ inputs.env }} ~/yaml/demo-helm/${{ inputs.module }}${{ inputs.env }}
