name: host deploy 
on: 
  workflow_call:
    inputs:
      module:
        required: true
        type: string
      env:
        required: false
        type: string
jobs:
  deploy:
    runs-on: [self-hosted]
    continue-on-error: true 
    steps:
      - if: inputs.env == 0
        run: |
          helm uninstall -n demo ${{ inputs.module }}
          
      - if: inputs.env != 0
        run: |
          helm uninstall -n demo ${{ inputs.module }}-${{ inputs.env }}
          
      - if: inputs.env == 0
        run: |
          helm install -n demo ${{ inputs.module }} ~/yaml/demo-helm/${{ inputs.module }}
      
      - if: inputs.env != 0
        run: |
          helm install -n demo ${{ inputs.module }}-${{ inputs.env }} ~/yaml/demo-helm/${{ inputs.module }}-${{ inputs.env }}

        
