name: Build on host
on: 
  workflow_call:
    secrets:
      VAULT_TOKEN: 
        description: 'vault.token'
        required: true
      VAULT_URI:
        description: 'vault.uri'
        required: true
      VAULT_PATH:
        description: 'vault.path'
        required: true
      SECRETS_PATH:
        description: 'SECRETS_PATH'
        required: true
jobs:
  host_build:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: [self-hosted]
    outputs:
      result: ${{ steps.build.outputs.build }}
    steps:      
      - name: Checkout
        uses: actions/checkout@v3.3.0
       
      - name: package 
        run: | 
          mvn package install -DskipTests
                    
      - id: build 
        run: |
          cd gateway
          mvn -DvaultToken=${{secrets.VAULT_TOKEN}} -DvaultPath=${{secrets.VAULT_PATH}} -DvaultUri=${{secrets.VAULT_URI}}  -DSECRETS_PATH=${{secrets.SECRETS_PATH}} -P native,nativeTest package -DskipTests
          podman tag registry.elpsykongroo.com/library/gateway:native gateway:native
          echo "build=success" >> $GITHUB_OUTPUT
          
      - name: Push To Registry
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: gateway
          registry: registry.elpsykongroo.com/library
          tags: "native"
          username:  ${{ secrets.REGISTRY_PRIVATE_NAME }}
          password:  ${{ secrets.REGISTRY_PRIVATE_PASS }}
  deploy:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    needs: host_build
#     if: needs.host_build.outputs.result == 'success'
    runs-on: [self-hosted]
    steps:
      - name: depoly with helm
        run: |
          helm upgrade -n demo demo ~/code/helm/charts/demo

#   label:
#     needs: host_build
#     if: needs.host-build.outputs.result == 'success'
#     environment: ${{ github.event.inputs.environment || 'native-image' }}
#     uses: Labman4/workflow/.github/workflows/labeler.yml@labeler
    


