name: Build on host
on: 
  workflow_call:
    secrets:
      VAULT_TOKEN: 
        description: 'vault.token'
        required: true
      VAULT_URI:
        description: 'vault.uri'
        required: true
      VAULT_PATH:
        description: 'vault.path'
        required: true
      SECRETS_PATH:
        description: 'SECRETS_PATH'
        required: true
    inputs:
      deploy_secret:
        type: string
        required: false
jobs:
  host_build:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: [self-hosted]
    outputs:
      result: ${{ steps.build.outputs.build }}
    steps:      
      - name: Checkout
        uses: actions/checkout@v3.3.0   
     
      - run: |
          echo "path=$(pwd)" >> $GITHUB_ENV
          echo "home=$HOME" >> $GITHUB_ENV
          
      - name: package 
        run: | 
          mvn package install -DskipTests
         
      - name: agent trace   
        run: |
          #nohup java -agentlib:native-image-agent=config-merge-dir=${{ env.path }}/gateway/src/main/resources/META-INF/native-image/ -DENV=pre -jar  ${{ env.path }}/gateway/target/gateway-0.0.2.jar > nohup.out 2> nohup.err < /dev/null & echo "pid=$!" >> $GITHUB_ENV  
          java -agentlib:native-image-agent=config-merge-dir=${{ env.path }}/gateway/src/main/resources/META-INF/native-image/ -DENV=pre -jar  gateway/target/gateway-0.0.2.jar 
          #echo "stopMarker=$(uuidgen)" >> $GITHUB_ENV
        continue-on-error: true 

      
      #- run: |
          #kill -s 2 ${{ env.pid }}
          #echo "::stop-commands::${{ env.stopMarker}}"
          #curl -X POST http://localhost:8080/actuator/shutdown
          
      #- run: |    
      #    cat ${{ env.path }}/gateway/src/main/resources/META-INF/native-image/.lock
      #    ps -ef |grep ${{ env.pid }}
          
      - id: build 
        run: |
          mvn -DvaultToken=${{secrets.VAULT_TOKEN}} -DvaultPath=${{secrets.VAULT_PATH}} -DvaultUri=${{secrets.VAULT_URI}}  -DSECRETS_PATH=${{secrets.SECRETS_PATH}} -P native,nativeTest package -DskipTests -f ${{ env.path }}/gateway/pom.xml
          podman tag registry.elpsykongroo.com/library/gateway:native gateway:native
          echo "build=success" >> $GITHUB_OUTPUT
          
      - name: Push To Registry
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: gateway
          registry: registry.elpsykongroo.com/library
          tags: "native"
          username:  ${{ secrets.REGISTRY_PRIVATE_NAME }}
          password:  ${{ secrets.REGISTRY_PRIVATE_PASS }}
          
  deploy:
    if: ${{ secrets.DEPLOY_SECRET }} == ${{ inputs.deploy_secret }}
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    needs: host_build
#     if: needs.host_build.outputs.result == 'success'
    runs-on: [self-hosted]
    steps:
      - name: depoly with helm
        run: |
          helm upgrade -n demo demo ~/code/helm/charts/demo

#   label:
#     needs: host_build
#     if: needs.host-build.outputs.result == 'success'
#     environment: ${{ github.event.inputs.environment || 'native-image' }}
#     uses: Labman4/workflow/.github/workflows/labeler.yml@labeler
    


