name: Build on host
on: 
  workflow_call:
  
jobs:
  host_build:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: [self-hosted]
    steps:      
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Build native image
        run: |
          mvn -Pnative,nativeTest package -DskipTests
