name: host deploy 
on: 
  workflow_call:
    inputs:
      module:
        description: 'module name'
        required: true
        type: string
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: depoly with helm
        run: |
          helm upgrade -n demo ${{ inputs.module }} ~/yaml/demo-helm/${{ inputs.module }}
