name: Build on host
on: 
  workflow_call:
    inputs:
      vault_token: 
        description: 'vault_token'
        required: false
        type: string

      vault_uri:
        description: 'vault_uri'
        required: false
        type: string

      vault_path:
        description: 'vault_path'
        required: false
        type: string

      secrets_path:
        description: 'secrets_path'
        required: false
        type: string 
  
jobs:
  host_build:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: [self-hosted]
    steps:      
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Set env
        run: |
          echo "vault.token=${{ inputs.vault_token }}" >> $GITHUB.ENV
          echo "vault.token=${{ inputs.vault_token }}" >> $GITHUB.ENV
          echo "vault.token=${{ inputs.vault_token }}" >> $GITHUB.ENV
          echo "vault.token=${{ inputs.vault_token }}" >> $GITHUB.ENV
       
      - name: Build native image
        run: |
          mvn -Pnative,nativeTest package -DskipTests
