name: Build on host
on: 
  workflow_call:
    inputs:
      vault_token: 
      vault_uri:
      vault_path:
      secrets_path:
        
  
jobs:
  host_build:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: [self-hosted]
    steps:      
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Set env
        run: |
          echo "vault.token=${{ inputs.vault_token }}" >> $GITHUB.ENV
          echo "vault.token=${{ inputs.vault_token }}" >> $GITHUB.ENV
          echo "vault.token=${{ inputs.vault_token }}" >> $GITHUB.ENV
          echo "vault.token=${{ inputs.vault_token }}" >> $GITHUB.ENV
       
      - name: Build native image
        run: |
          mvn -Pnative,nativeTest package -DskipTests
