name: Build on host
on: 
  workflow_call:
    secrets:
      VAULT_TOKEN: 
        description: 'vault.token'
        required: true

      VAULT_URI:
        description: 'vault.uri'
        required: true

      VAULT_PATH:
        description: 'vault.path'
        required: true

      SECRETS_PATH:
        description: 'SECRETS_PATH'
        required: true
  
jobs:
  host_build:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: [self-hosted]
    steps:      
       - name: Download a Build Artifact
         uses: actions/download-artifact@v3.0.1
         with:
           name:  package
       
       - name: Build native image
         run: |
           mvn -DvaultToken=${{secrets.VAULT_TOKEN}} -DvaultPath=${{secrets.VAULT_PATH}} -DvaultUri=${{secrets.VAULT_URI}}  -DSECRETS_PATH=${{secrets.SECRETS_PATH}} -P native,nativeTest package -DskipTests 
