name: Build on host
on: 
  workflow_call:
    secrets:
      VAULT_TOKEN: 
        description: 'vault.token'
        required: true

      VAULT_URI:
        description: 'vault.uri'
        required: true

      VAULT_PATH:
        description: 'vault.path'
        required: true

      SECRETS_PATH:
        description: 'SECRETS_PATH'
        required: true
  
jobs:
  host_build:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: [self-hosted]
    steps:      
      - name: Checkout
        uses: actions/checkout@v3.3.0
       
      - name: Build native image
        env: 
          vaultToken: ${{ secrets.VAULT_TOKEN }}
          vaultUri: ${{ secrets.VAULT_URI }}
          vaultPath: ${{ secrets.VAULT_PATH }}
          SECRETS_PATH: ${{ secrets.SECRETS_PATH }}
        run: |
          mvn -DvaultToken={{secrets.VAULT_TOKEN}} -DvaultPath={{secrets.VAULT_PATH}} -DvaultUri={{secrets.VAULT_URI}} -P native,nativeTest package -DskipTests 
