name: "Labeler"
on:
#   pull_request_target:
  workflow_call:
    inputs:
      configuration-path:
        description: 'label rulers'
#         default: '.github/labeler.yml'
        required: true
        type: string
        
  pull_request:
    types: [ opened, synchronize, reopened ]
env:
  PR_NUMBER: ${{ github.event.number }}
   
jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ${{ inputs.configuration-path }}

