on: 
  workflow_call:

jobs:
  set-up:
    uses: Labman4/workflow/.github/workflows/graalvm.yml@set-up    
    
  update:
    needs: set-up
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-concurrency-for-cache-maven
      cancel-in-progress: false
    steps:              
    - run: |
        rm -rf ~/.m2/repository/
        
    - run: |
        mvn clean package install -DskipTests
  
