on: 
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    concurrency: "1"
    steps:  
    - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
        
    - uses: actions/cache@v3.2.2
      with:
        path: ~/.m2/repository
        key:  setup-graalvm-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          setup-graalvm-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          
    - run: |
        mvn package install -DskipTests
  
