on: 
  workflow_call:

jobs:    
  update:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-concurrency-for-cache-maven
      cancel-in-progress: false
    steps:  
    - uses: actions/checkout@v3.5.3
   
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: setup-graalvm-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          setup-graalvm-${{ runner.os }}-maven-
      
    - run: |
        rm -rf ~/.m2/repository/com/elpsykongroo
        
    - run: |
        mvn clean package install -DskipTests
  
