on: 
  workflow_call:

jobs:
  set-up:
    uses: Labman4/workflow/.github/workflows/graalvm.yml@set-up    
    
  update:
    needs: set-up
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-concurrency-for-cache-maven
      cancel-in-progress: false
    steps:  
    - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
            
    - run: |
        rm -rf ~/.m2/repository/com/elpsykongroo/
        rm -rf ~/.m2/repository/com/google/guava/
    - run: |
        mvn clean package install -DskipTests
  
