on: 
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-concurrency-for-cache-maven
      cancel-in-progress: false
    steps:  
    - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
             
    - uses: graalvm/setup-graalvm@b11d36630f94ed5864e0a680a979b5afde449e9d
      with:
        version: 'latest'
        java-version: '17'
        set-java-home: 'true'
        cache: maven
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - run: |
        rm -rf ~/.m2/repository/com/elpsykongroo/
        
    - run: |
        mvn clean package install -DskipTests
  
