name: Native image
on:
  workflow_call:
    inputs:
      configuration-path:
        description: 'label rulers'
#         default: '.github/labeler.yml'
        required: true
        type: string
  push:
    branches:
    - develop
    
  pull_request:
    branches:
    - native-image
    
jobs:
  test:
    environment: native-image
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
            
      - name: Set up Graalvm
        uses: graalvm/setup-graalvm@d01f5f519f35cf82b318133761fd8b674632a8fe
        with:
          version: 'latest'
          java-version: '17'
          set-java-home: 'true'
          cache: maven
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'
       
      - name: Cache local Maven repository
        uses: actions/cache@v3.2.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 
            
      - name: trace agent
        run: |
          mvn package -DskipTests
          java -agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/ -jar target/demo-0.0.2.jar      
            
      - name: Web test
        run: |
          mvn -Pnative,nativeTest -Dagent=true test  
            
      - name: Merge native config
        run: |
          native-image --macro:native-image-configure-launcher
          native-image-configure generate --input-dir=target/native/agent-output/test --output-dir=src/main/resources/META-INF/native-image
          #--input-dir=target/native/agent-output/main 
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ env.name }}-build
          path: |
            src/
            target/
            pom.xml
          retention-days: 3  
          
      - name: Upload test report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: test
          path: '**/target/surefire-reports/TEST-*.xml'
           
      - name: Create pull request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
      
      - uses: actions/labeler@v4
        env: 
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ${{ inputs.configuration-path }}

  label:
    permissions:
      contents: read
      pull-requests: write
    needs: test
    uses: Labman4/workflow/.github/workflows/labeler.yml@labeler 
    with:
      configuration-path: .github/labeler.yml
 
  automerge:
    needs: label
    uses: Labman4/workflow/.github/workflows/automerge.yml@automerge
   
#   pre-build:
#     uses: Labman4/workflow/.github/workflows/pre-build.yml@native-image
    
#   build:
#     needs: automerge
#     uses: Labman4/workflow/.github/workflows/build-native-image.yml@native-image
    
  buildpacks:
    needs: test
    uses: Labman4/workflow/.github/workflows/buildpacks.yml@buildpacks
    
  codescan:
    uses: Labman4/workflow/.github/workflows/codescan-java.yml@codescan-java
    
  coverage:  
    needs: test
    uses: Labman4/workflow/.github/workflows/coverage-reporter.yml@coverage
    
  
