name: Native image (base)
on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
      module:
        required: true
        type: string
      moduleName:
        required: false
        type: string
      version:
        required: true
        type: string

jobs:
  cache: 
    uses: Labman4/workflow/.github/workflows/maven.yml@cache
    
  test:
    needs: cache
    environment: native-image
    runs-on: [ubuntu-latest]
    steps:
      - if: inputs.moduleName == 0
        run: echo "modulePath=${{ inputs.module }}" >> $GITHUB_ENV
      
      - if: inputs.moduleName != 0
        run: echo "modulePath=${{ inputs.module }}/${{ inputs.moduleName }}"  >> $GITHUB_ENV
        
      - uses: ScribeMD/docker-cache@0.3.3
        with:
          key: docker-${{ runner.os }}-${{ github.workflow_ref }}
          
      - uses: actions/checkout@v3.5.3
                  
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          set-java-home: 'true'
          cache: maven
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'
               
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2.7.3
        with:
          url: https://vault.elpsykongroo.com:443
          method: github
          githubToken: ${{ secrets.VAULT_GITHUB_TOKEN }}
          secrets: |
              kv/data/app/test/redis $.$ 
 
     
      - run: |
          echo "path=$(pwd)" >> $GITHUB_ENV
          echo "home=$HOME" >> $GITHUB_ENV
          echo "${{service.redis.port}}"
          java --version
          
      - run: | 
          mvn package install -DskipTests -f  ${{ env.path }}/${{ env.modulePath }}/pom.xml    
          
#       - run: |
#           mvn -P native,nativeTest -Dagent=true test -f  ${{ env.path }}/${{ env.modulePath }}/pom.xml                
       
#       - run: |
#           native-image --macro:native-image-configure-launcher
      
#       - run: |
#           native-image-configure generate --input-dir=${{ env.path }}/${{ env.modulePath }}/target/native/agent-output/test --output-dir=${{ env.path }}/${{ env.modulePath }}/src/main/resources/META-INF/native-image
#           #--input-dir=target/native/agent-output/main 
      
#       - run: |
#           git status
      
#       - uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
      
      - run: |
          nohup java -agentlib:native-image-agent=config-merge-dir=${{ env.path }}/${{ env.modulePath }}/src/main/resources/META-INF/native-image/ -jar  ${{ env.modulePath }}/target/${{ inputs.moduleName }}-${{ inputs.version }}.jar > /dev/null 2>&1  & echo "pid=$!" >> $GITHUB_ENV  
          #echo "stopMarker=$(uuidgen)" >> $GITHUB_ENV
        continue-on-error: true 
  
      - run: |
          git status
          
#       - uses: actions/upload-artifact@v3.1.1
#         with:
#           name: test
#           path: '**/target/surefire-reports/TEST-*.xml'
  
      - run: |
          #echo "::stop-commands::${{ env.stopMarker}}"
          sleep 15
          kill -s 15 ${{ env.pid }}
          sleep 15
          #curl -X POST http://localhost:8080/actuator/shutdown
        continue-on-error: true 

      - run: | 
         ps -ef |grep ${{ env.pid }}
        
      - run: |
          git status
          
      - id: cpr
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          base: native-image
      
      - run: |
          git status
          
      - run: |
          mvn -P native package -DskipTests -f  ${{ env.path }}/${{ env.modulePath }}/pom.xml 
        
      - run: |
          git status
          
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: package
          path: |
            ${{ env.path }}
            !${{ env.path }}/**/*.jar
          retention-days: 3  

  pre-build:
    needs: test
    uses: Labman4/workflow/.github/workflows/buildpacks-native.yml@buildpacks
    secrets: inherit
    with:
      module: ${{ inputs.module }}
      moduleName: ${{ inputs.moduleName }}
      
    
  deploy:
    needs: pre-build
    uses: Labman4/workflow/.github/workflows/deploy.yml@deploy
    with: 
      module: ${{ inputs.module }}
      
    
  
