name: Native image
on:
  workflow_call:
    secrets:
      VAULT_TOKEN: 
        description: 'vault.token'
        required: true
      VAULT_URI:
        description: 'vault.uri'
        required: true
      VAULT_PATH:
        description: 'vault.path'
        required: true
      SECRETS_PATH:
        description: 'SECRETS_PATH'
        required: true 
jobs:
  test:
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
            
      - name: Set up Graalvm
        uses: graalvm/setup-graalvm@d01f5f519f35cf82b318133761fd8b674632a8fe
        with:
          version: 'latest'
          java-version: '17'
          set-java-home: 'true'
          cache: maven
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'
       
      - name: Cache local Maven repository
        uses: actions/cache@v3.2.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 
            
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11   
        
#       - name: trace agent
#         run: |
#           mvn package -DskipTests
#           java -agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/ -jar target/demo-0.0.2.jar     
#           echo -e '\003'
        
      - name: package
        run: |
          mvn -P native package -DskipTests
         
      - name: Upload a package
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ env.name }}-package
          path: |
            src/
            target/
            pom.xml
          retention-days: 3  
          
      - name: Web test
        run: |
          mvn clean -DvaultToken=${{secrets.VAULT_TOKEN}} -DvaultPath=${{secrets.VAULT_PATH}} -DvaultUri=${{secrets.VAULT_URI}}  -DSECRETS_PATH=${{secrets.SECRETS_PATH}} -P native,nativeTest -Dagent=true test    
            
      - name: Merge native config
        run: |
          native-image --macro:native-image-configure-launcher
          native-image-configure generate --input-dir=target/native/agent-output/test --output-dir=src/main/resources/META-INF/native-image
          #--input-dir=target/native/agent-output/main 
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ env.name }}-build
          path: |
            src/
            target/
            pom.xml
          retention-days: 3  
          
      - name: Upload test report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: test
          path: '**/target/surefire-reports/TEST-*.xml'
           
      - name: Create pull request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          base: native-image
      
  pr_number:
    needs: test
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
        with:
          fetch-depth: 0
      - name: Get Pull Request Number
        id: pr
        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.pr.outputs.pull_request_number }}

    
#   automerge:
#     needs: labeler
#     uses: Labman4/workflow/.github/workflows/automerge.yml@automerge

  build:
    needs: test
    uses: Labman4/workflow/.github/workflows/host-build-native-from-pre.yml@native-image
    secrets: inherit
   
  pre-build:
    uses: Labman4/workflow/.github/workflows/buildpacks-native.yml@buildpacks
    
#   buildpacks:
#     needs: test
#     uses: Labman4/workflow/.github/workflows/buildpacks-native.yml@buildpacks
    
#   coverage:  
#     needs: test
#     uses: Labman4/workflow/.github/workflows/coverage-reporter.yml@coverage
    
  
