name: Native image (base)
on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
      moduleName:
        required: false
        type: string
      version:
        required: true
        type: string
      native:
        required: false
        type: boolean
      secretPath:
        required: true
        type: string

jobs:
  cache: 
    uses: Labman4/workflow/.github/workflows/maven.yml@cache
    
  test:
    needs: cache
    runs-on: [ubuntu-latest]
    steps:
      - if: inputs.moduleName == 0
        run: echo "modulePath=${{ inputs.module }}" >> $GITHUB_ENV
      
      - if: inputs.moduleName != 0
        run: echo "modulePath=${{ inputs.module }}/${{ inputs.moduleName }}"  >> $GITHUB_ENV
        
      - uses: ScribeMD/docker-cache@0.3.3
        with:
          key: docker-${{ runner.os }}-${{ github.workflow_ref }}
          
      - uses: actions/checkout@v3.5.3
          
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          set-java-home: 'true'
          cache: maven
          github-token: ${{ secrets.GITHUB_TOKEN }}
          components: 'native-image'
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'

      - if: ${{inputs.native  && github.ref_name == 'main' }}
        name: Import Secrets
        uses: hashicorp/vault-action@v2.7.3
        with:
          url: ${{ secrets.VAULT_URI }}
          method: github
          githubToken: ${{ secrets.VAULT_GITHUB_TOKEN }}
          secrets: |
            kv/data/app/test/vault VAULT_TOKEN | VAULT_TOKEN;
            kv/data/app/test/vault VAULT_URI | VAULT_URI;
            kv/data/app/test/vault SECRETS_APP_BASE_PATH | SECRETS_APP_BASE_PATH;            

      - if: ${{inputs.native  && github.ref_name == 'develop' }}
        name: Import Secrets
        uses: hashicorp/vault-action@v2.7.3
        with:
          url: ${{ secrets.VAULT_URI }}
          method: github
          githubToken: ${{ secrets.VAULT_GITHUB_TOKEN }}
          secrets: |
            kv/data/app/test/vault VAULT_TOKEN | VAULT_TOKEN;
            kv/data/app/test/vault VAULT_URI | VAULT_URI;
            kv/data/app/test/vault SECRETS_APP_NATIVE_BASE_PATH | SECRETS_APP_BASE_PATH;
            
      - run: |
          echo "path=$(pwd)" >> $GITHUB_ENV
          echo "SECRETS_APP_PATH=${{ inputs.secretPath }}"  >> $GITHUB_ENV
          lsmod | grep ipv6
          ip -6 addr
          java --version
          
      - run: | 
          mvn clean package install -DskipTests 
          
      - run: |
          mvn spring-boot:build-image  -DskipTests -f  ${{ env.path }}/${{ env.modulePath}}/pom.xml  
          
      - run: |
          docker tag ${{inputs.module}}:${{inputs.version}} ${{inputs.module}}:${{ github.event.inputs.ref || github.head_ref || github.ref_name }}
        continue-on-error: true 
  
      - name: Push To quay
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ inputs.module }}
          registry: quay.io/elpsykongroo
          tags: ${{ github.ref_name	}}
          username:  ${{ secrets.QUAY_REGISTRY_NAME }}
          password:  ${{ secrets.QUAY_REGISTRY_PASS }} 
        continue-on-error: true 
      
      - run: |
          docker tag ${{inputs.module}}:${{inputs.version}} ${{inputs.module}}:${{github.sha}}
          
      - name: Push To quay ref
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ inputs.module }}
          registry: quay.io/elpsykongroo
          tags: ${{github.sha}}
          username:  ${{ secrets.QUAY_REGISTRY_NAME }}
          password:  ${{ secrets.QUAY_REGISTRY_PASS }} 

      - if:  ${{ github.ref_name == 'main' }}
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ inputs.module }}
          registry: quay.io/elpsykongroo
          tags: ${{inputs.version }}
          username:  ${{ secrets.QUAY_REGISTRY_NAME }}
          password:  ${{ secrets.QUAY_REGISTRY_PASS }} 

      - name: Push To harbor
        uses: redhat-actions/push-to-registry@v2.7
        continue-on-error: true
        timeout-minutes: 10     
        with:
          image: ${{ inputs.module }}
          registry: registry.elpsykongroo.com/library
          tags: ${{ github.ref_name	}}
          username:  ${{ secrets.REGISTRY_PRIVATE_NAME }}
          password:  ${{ secrets.REGISTRY_PRIVATE_PASS }}
          
#       - run: |
#           mvn -P native,nativeTest -Dagent=true test -f  ${{ env.path }}/${{ env.modulePath }}/pom.xml                
       
#       - run: |
#           native-image --macro:native-image-configure-launcher
      
#       - run: |
#           native-image-configure generate --input-dir=${{ env.path }}/${{ env.modulePath }}/target/native/agent-output/test --output-dir=${{ env.path }}/${{ env.modulePath }}/src/main/resources/META-INF/native-image
#           #--input-dir=target/native/agent-output/main 
      
#       - uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04

      - if: inputs.moduleName != 0
        run: |
          nohup java -agentlib:native-image-agent=config-merge-dir=${{ env.path }}/${{ env.modulePath }}/src/main/resources/META-INF/native-image/ -jar  ${{ env.modulePath }}/target/${{ inputs.moduleName }}-${{ inputs.version }}.jar > /dev/null 2>&1  & echo "pid=$!" >> $GITHUB_ENV  
        continue-on-error: true 
  
      - if: inputs.moduleName == 0
        run: |
          #java -agentlib:native-image-agent=config-merge-dir=${{ env.path }}/${{ env.modulePath }}/src/main/resources/META-INF/native-image/ -jar  ${{ env.modulePath }}/target/${{ inputs.module }}-${{ inputs.version }}.jar 
          nohup java -agentlib:native-image-agent=config-merge-dir=${{ env.path }}/${{ env.modulePath }}/src/main/resources/META-INF/native-image/ -jar  ${{ env.modulePath }}/target/${{ inputs.module }}-${{ inputs.version }}.jar > /dev/null 2>&1  & echo "pid=$!" >> $GITHUB_ENV  
        continue-on-error: true 
        
      - run: |
          git status
          
#       - uses: actions/upload-artifact@v3.1.1
#         with:
#           name: test
#           path: '**/target/surefire-reports/TEST-*.xml'
      - run: | 
         ps -ef |grep ${{ env.pid }}
        continue-on-error: true 

      - run: |
          sleep 15
          kill -s 15 ${{ env.pid }}
          sleep 15
          #curl -X POST http://localhost:8080/actuator/shutdown
        continue-on-error: true 

      - run: | 
         ps -ef |grep ${{ env.pid }}
        continue-on-error: true 

      - run: |
          git status
        
      - if: inputs.native
        run: |
          mvn -P native spring-boot:build-image  -DskipTests -f  ${{ env.path }}/${{ env.modulePath}}/pom.xml
          
      - run: |
          docker tag ${{inputs.module}}:native ${{inputs.module}}:${{ github.event.inputs.ref || github.head_ref || github.ref_name }}-native
        continue-on-error: true 

      - run: |
          docker tag ${{inputs.module}}:native ${{inputs.module}}:${{ inputs.version }}-native
        continue-on-error: true 
        
      - run: |
          docker tag ${{inputs.module}}:native ${{inputs.module}}:${{ github.sha }}-native
        continue-on-error: true 
        
      - if: inputs.native
        name: Push To quay
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ inputs.module }}
          registry: quay.io/elpsykongroo
          tags: ${{github.ref_name }}-native
          username:  ${{ secrets.QUAY_REGISTRY_NAME }}
          password:  ${{ secrets.QUAY_REGISTRY_PASS }}     
          
      - if: inputs.native
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ inputs.module }}
          registry: quay.io/elpsykongroo
          tags: ${{ github.sha }}-native
          username:  ${{ secrets.QUAY_REGISTRY_NAME }}
          password:  ${{ secrets.QUAY_REGISTRY_PASS }}     

      - if: ${{inputs.native  && github.ref_name == 'main' }}
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ inputs.module }}
          registry: quay.io/elpsykongroo
          tags: ${{ inputs.version }}-native
          username:  ${{ secrets.QUAY_REGISTRY_NAME }}
          password:  ${{ secrets.QUAY_REGISTRY_PASS }} 
          
      # - id: cpr
      #   uses: peter-evans/create-pull-request@v5.0.2
      
      - run: |
          git status
          
#       - run: |
#           mvn -P native package -DskipTests -f  ${{ env.path }}/${{ env.modulePath }}/pom.xml 
        
#       - run: |
#           git status
          
#       - uses: actions/upload-artifact@v3.1.2
#         with:
#           name: package
#           path: |
#             ${{ env.path }}
#             !${{ env.path }}/**/*.jar
#           retention-days: 3  

#   pre-build:
#     needs: test
#     uses: Labman4/workflow/.github/workflows/buildpacks-native.yml@buildpacks
#     secrets: inherit
#     with:
#       module: ${{ inputs.module }}
#       moduleName: ${{ inputs.moduleName }}
      
    
#   deploy:
#     needs: test
#     uses: Labman4/workflow/.github/workflows/deploy.yml@deploy
#     with: 
#       module: ${{ inputs.module }}
      
    
  
