name: host deploy dev
on: 
  workflow_call:
jobs:
  deploy:
    environment: dev
    runs-on: [self-hosted]
    steps:
      - name: depoly with helm
        run: |
          helm upgrade -n demo demo-dev ~/yaml/demo-helm/demo-dev
