name: build or deploy
on: 
  workflow_call:
#     inputs:
#       deploy_secret:
#         type: string
#         required: false
jobs:
  auth:
    uses: Labman4/workflow/.github/workflows/native-image-postgres.yml@native-image
    secrets: inherit
    with:
      module: auth
      version: 0.0.2
      native: false
      secretPath: kv/app/native/auth
      
  gateway: 
    needs: auth
    uses: Labman4/workflow/.github/workflows/native-image-gateway.yml@native-image
    secrets: inherit
    with:
      module: gateway
      version: 0.0.2
      native: false
      secretPath: kv/app/native/gateway
      
  message: 
    needs: gateway
    uses: Labman4/workflow/.github/workflows/native-image-base.yml@native-image
    secrets: inherit
    with:
      module: message
      version: 0.0.1
      native: false
      secretPath: kv/app/native/message
      
  redis:
    uses: Labman4/workflow/.github/workflows/native-image-redis.yml@native-image
    secrets: inherit
    with:
      module: redis
      version: 0.0.1
      native: false
      secretPath: kv/app/native/redis
      
  elasticsearch:
    needs: redis
    uses: Labman4/workflow/.github/workflows/native-image-elasticsearch.yml@native-image
    secrets: inherit
    with:
      module: elasticsearch
      version: 1.0.0
      native: false
      secretPath: kv/app/native/es
  
  storage:
    needs: elasticsearch
    uses: Labman4/workflow/.github/workflows/native-image-base.yml@native-image
    secrets: inherit
    with:
      module: storage
      version: 1.0.0
      native: false
      secretPath: kv/app/native/storage
      
  kafka:
    needs: gateway
    uses: Labman4/workflow/.github/workflows/native-image-kafka.yml@native-image
    secrets: inherit
    with:
      module: kafka
      version: 0.0.1
      native: false
      secretPath: kv/app/native/kafka
